### ISSUE TITLE
Parsing of queries before execution

### ISSUE THREAD

**Issue by buzoherbert** [urbanlaunchpad/ftAPI#17]
The queries should be parsed before the server does any data operation or return of information.

If a query fails, nothing should be done in the database and an error should be returned with the possible location of the problem

**Comment by SRIVARDH001** [comment]
Fixed issue by introducing SAVE POINTS , COMMITS and ROLLBACK features of sql for implementing Do everything or else Do Nothing and thereby get back to safe old state of the DB!
