### ISSUE TITLE
Wrong hierarchy on the team

### ISSUE THREAD

**Issue by buzoherbert** [urbanlaunchpad/ftAPI#44]
The current url is

webapi/team/<owner>/projects/<project_name>

It should be 

webapi/<owner>/projects/<project_name>/team/

**Comment by SRIVARDH001** [comment]
Changed to
webapi/users/ownerName/projects/projectName/team   
In both the server and API

**Comment by SRIVARDH001** [comment]
Changed webapi/users/ownerName/projects/projectName/team to
webapi/ownerName/projects/projectName/team as the former created a resource clash and messed the server's working.
